[2025-01-17T17:08:01.321+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T17:08:01.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T17:08:01.407+0000] {taskinstance.py:1361} INFO - Starting attempt 12 of 12
[2025-01-17T17:08:01.435+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-16 00:00:00+00:00
[2025-01-17T17:08:01.490+0000] {standard_task_runner.py:57} INFO - Started process 1751 to run task
[2025-01-17T17:08:01.568+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'load_data', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmp13j3i469']
[2025-01-17T17:08:01.637+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask load_data
[2025-01-17T17:08:02.118+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.load_data scheduled__2025-01-16T00:00:00+00:00 [running]> on host 4e4dfd1b49e6
[2025-01-17T17:08:02.357+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-01-17T17:08:02.880+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:03.014+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.user_profiling (
            user_id INT,
            name TEXT,
            timestamp TIMESTAMP,
            membership_type TEXT,
            membership_purchase_status TEXT,
            mdr_percentage FLOAT,
            first_transaction TIMESTAMP,
            invoice_total_count INT,
            invoice_total_amount FLOAT
        );
        , parameters: None
[2025-01-17T17:08:03.109+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:03.143+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.transaction_totals_per_type (
            timestamp TIMESTAMP,
            membership_type TEXT,
            invoice_total_count INT,
            invoice_total_amount FLOAT
        );
        , parameters: None
[2025-01-17T17:08:03.224+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:03.248+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.daily_activity_report (
            timestamp TIMESTAMP,
            invoice_total_count INT,
            invoice_total_amount FLOAT
        );
        , parameters: None
[2025-01-17T17:08:03.348+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:03.438+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.transactions_mdr (
            transaction_id INT,
            user_id int,
            transaction_amount float,
            timestamp TIMESTAMP,
            name TEXT,
            email TEXT,
            phone TEXT,
            membership_id FLOAT,
            membership_type TEXT,
            purchase_date DATE,
            expiry_date DATE,
            mdr_id FLOAT,
            mdr_percentage FLOAT,
            membership_purchase_status TEXT,
            effective_amount FLOAT
        );
        , parameters: None
[2025-01-17T17:08:03.710+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:03.908+0000] {sql.py:515} INFO - Done loading. Loaded a total of 28 rows into sprout.user_profiling
[2025-01-17T17:08:04.063+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:04.437+0000] {sql.py:515} INFO - Done loading. Loaded a total of 10 rows into sprout.transaction_totals_per_type
[2025-01-17T17:08:04.640+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:04.864+0000] {sql.py:515} INFO - Done loading. Loaded a total of 6 rows into sprout.daily_activity_report
[2025-01-17T17:08:05.118+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T17:08:05.496+0000] {db_to_xls.py:232} ERROR - Error during data loading: can't adapt type 'NAType'
[2025-01-17T17:08:05.508+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/db_to_xls.py", line 224, in load_data
    postgres_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 509, in insert_rows
    cur.execute(sql, values)
psycopg2.ProgrammingError: can't adapt type 'NAType'
[2025-01-17T17:08:05.662+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=load_data, execution_date=20250116T000000, start_date=20250117T170801, end_date=20250117T170805
[2025-01-17T17:08:05.810+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task load_data (can't adapt type 'NAType'; 1751)
[2025-01-17T17:08:06.206+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T17:08:06.578+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
