[2025-01-17T16:58:02.525+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T16:58:02.889+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_with_excel_report.load_data scheduled__2025-01-16T00:00:00+00:00 [queued]>
[2025-01-17T16:58:02.903+0000] {taskinstance.py:1361} INFO - Starting attempt 10 of 10
[2025-01-17T16:58:03.169+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2025-01-16 00:00:00+00:00
[2025-01-17T16:58:03.394+0000] {standard_task_runner.py:57} INFO - Started process 1632 to run task
[2025-01-17T16:58:03.535+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_process_with_excel_report', 'load_data', 'scheduled__2025-01-16T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/db_to_xls.py', '--cfg-path', '/tmp/tmpblmbo4ub']
[2025-01-17T16:58:03.702+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask load_data
[2025-01-17T16:58:05.407+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_process_with_excel_report.load_data scheduled__2025-01-16T00:00:00+00:00 [running]> on host 4e4dfd1b49e6
[2025-01-17T16:58:06.569+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_process_with_excel_report' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-16T00:00:00+00:00'
[2025-01-17T16:58:07.261+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:07.300+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.user_profiling (
            user_id INT,
            name TEXT,
            timestamp TIMESTAMP,
            membership_type TEXT,
            membership_purchase_status TEXT,
            mdr_percentage FLOAT,
            first_transaction TIMESTAMP,
            invoice_total_count INT,
            invoice_total_amount FLOAT
        );
        , parameters: None
[2025-01-17T16:58:07.329+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:07.348+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.transaction_totals_per_type (
            timestamp TIMESTAMP,
            membership_type TEXT,
            invoice_total_count INT,
            invoice_total_amount FLOAT
        );
        , parameters: None
[2025-01-17T16:58:07.371+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:07.396+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.daily_activity_report (
            timestamp TIMESTAMP,
            invoice_total_count INT,
            invoice_total_amount FLOAT
        );
        , parameters: None
[2025-01-17T16:58:07.495+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:07.519+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS sprout.transactions_with_mdr (
            transaction_id INT,
            user_id int,
            transaction_amount float,
            timestamp TIMESTAMP,
            name TEXT,
            email TEXT,
            phone TEXT,
            membership_id FLOAT,
            membership_type TEXT,
            purchase_date DATE,
            expiry_date DATE,
            mdr_id FLOAT,
            mdr_percentage FLOAT,
            membership_purchase_status TEXT,
            effective_amount FLOAT
        );
        , parameters: None
[2025-01-17T16:58:07.620+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:08.142+0000] {sql.py:515} INFO - Done loading. Loaded a total of 28 rows into sprout.user_profiling
[2025-01-17T16:58:08.299+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:08.416+0000] {sql.py:515} INFO - Done loading. Loaded a total of 10 rows into sprout.transaction_totals_per_type
[2025-01-17T16:58:08.514+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:08.565+0000] {sql.py:515} INFO - Done loading. Loaded a total of 6 rows into sprout.daily_activity_report
[2025-01-17T16:58:08.663+0000] {base.py:73} INFO - Using connection ID 'local_***' for task execution.
[2025-01-17T16:58:08.796+0000] {db_to_xls.py:232} ERROR - Error during data loading: can't adapt type 'NAType'
[2025-01-17T16:58:08.802+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/db_to_xls.py", line 224, in load_data
    postgres_hook.insert_rows(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 509, in insert_rows
    cur.execute(sql, values)
psycopg2.ProgrammingError: can't adapt type 'NAType'
[2025-01-17T16:58:08.927+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_process_with_excel_report, task_id=load_data, execution_date=20250116T000000, start_date=20250117T165802, end_date=20250117T165808
[2025-01-17T16:58:09.038+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 53 for task load_data (can't adapt type 'NAType'; 1632)
[2025-01-17T16:58:09.275+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-01-17T16:58:09.406+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
